"use strict";

const demoPassword = "password";
const tokens = new Map();

function isoMinutesAgo(minutes) {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

function createSeedState() {
  return {
    permissions: [
      {
        id: 1,
        name: "manage.users",
        group: "users",
        guard_name: "web",
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
      {
        id: 2,
        name: "manage.roles",
        group: "users",
        guard_name: "web",
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
      {
        id: 3,
        name: "manage.permissions",
        group: "users",
        guard_name: "web",
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
      {
        id: 4,
        name: "manage.learning",
        group: "learning",
        guard_name: "web",
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
      {
        id: 5,
        name: "manage.assessments",
        group: "assessment",
        guard_name: "web",
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
    ],
    roles: [
      {
        id: 1,
        name: "superadmin",
        guard_name: "web",
        permission_ids: [1, 2, 3, 4, 5],
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
      {
        id: 2,
        name: "manager",
        guard_name: "web",
        permission_ids: [4, 5],
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
      {
        id: 3,
        name: "employee",
        guard_name: "web",
        permission_ids: [],
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
    ],
    users: [
      {
        id: 1,
        name: "Demo Admin",
        email: "demo@example.com",
        password: demoPassword,
        email_verified_at: isoMinutesAgo(5800),
        role_ids: [1],
        permission_ids: [],
        profile_id: 1,
        is_logged_in: false,
        last_logged_in_at: isoMinutesAgo(15),
        last_logged_in_host: "127.0.0.1",
        last_logged_in_port: "5173",
        last_logged_in_user_agent: "Codex Mock Browser",
        last_logged_in_device: "Desktop",
        last_logged_in_browser: "Chromium",
        last_logged_in_platform: "Windows",
        created_at: isoMinutesAgo(5900),
        updated_at: isoMinutesAgo(200),
      },
      {
        id: 2,
        name: "Sara Manager",
        email: "sara.manager@example.com",
        password: demoPassword,
        email_verified_at: isoMinutesAgo(5500),
        role_ids: [2],
        permission_ids: [],
        profile_id: 2,
        is_logged_in: false,
        last_logged_in_at: isoMinutesAgo(35),
        last_logged_in_host: "10.10.1.20",
        last_logged_in_port: "443",
        last_logged_in_user_agent: "Mozilla/5.0 Mock",
        last_logged_in_device: "Laptop",
        last_logged_in_browser: "Chrome",
        last_logged_in_platform: "Windows",
        created_at: isoMinutesAgo(5600),
        updated_at: isoMinutesAgo(180),
      },
      {
        id: 3,
        name: "Agus Engineer",
        email: "agus.engineer@example.com",
        password: demoPassword,
        email_verified_at: isoMinutesAgo(5200),
        role_ids: [3],
        permission_ids: [],
        profile_id: 3,
        is_logged_in: false,
        last_logged_in_at: isoMinutesAgo(55),
        last_logged_in_host: "10.10.1.33",
        last_logged_in_port: "443",
        last_logged_in_user_agent: "Mozilla/5.0 Mock",
        last_logged_in_device: "Laptop",
        last_logged_in_browser: "Chrome",
        last_logged_in_platform: "Windows",
        created_at: isoMinutesAgo(5300),
        updated_at: isoMinutesAgo(120),
      },
      {
        id: 4,
        name: "Dina Engineer",
        email: "dina.engineer@example.com",
        password: demoPassword,
        email_verified_at: isoMinutesAgo(5100),
        role_ids: [3],
        permission_ids: [],
        profile_id: 4,
        is_logged_in: false,
        last_logged_in_at: isoMinutesAgo(75),
        last_logged_in_host: "10.10.1.41",
        last_logged_in_port: "443",
        last_logged_in_user_agent: "Mozilla/5.0 Mock",
        last_logged_in_device: "Desktop",
        last_logged_in_browser: "Edge",
        last_logged_in_platform: "Windows",
        created_at: isoMinutesAgo(5200),
        updated_at: isoMinutesAgo(90),
      },
      {
        id: 5,
        name: "Rani HR",
        email: "rani.hr@example.com",
        password: demoPassword,
        email_verified_at: isoMinutesAgo(5000),
        role_ids: [2],
        permission_ids: [],
        profile_id: 5,
        is_logged_in: false,
        last_logged_in_at: isoMinutesAgo(95),
        last_logged_in_host: "10.10.1.52",
        last_logged_in_port: "443",
        last_logged_in_user_agent: "Mozilla/5.0 Mock",
        last_logged_in_device: "Desktop",
        last_logged_in_browser: "Chrome",
        last_logged_in_platform: "Windows",
        created_at: isoMinutesAgo(5100),
        updated_at: isoMinutesAgo(80),
      },
      {
        id: 6,
        name: "Budi Learning",
        email: "budi.learning@example.com",
        password: demoPassword,
        email_verified_at: isoMinutesAgo(4900),
        role_ids: [3],
        permission_ids: [],
        profile_id: 6,
        is_logged_in: false,
        last_logged_in_at: isoMinutesAgo(105),
        last_logged_in_host: "10.10.1.60",
        last_logged_in_port: "443",
        last_logged_in_user_agent: "Mozilla/5.0 Mock",
        last_logged_in_device: "Laptop",
        last_logged_in_browser: "Chrome",
        last_logged_in_platform: "Windows",
        created_at: isoMinutesAgo(5000),
        updated_at: isoMinutesAgo(70),
      },
    ],
    profiles: [
      {
        id: 1,
        profile_fullname: "Demo Admin",
        profile_gender: "Male",
        profile_place_of_birth: "Jakarta",
        profile_date_of_birth: "1988-01-10",
        profile_marital_status: "Married",
        profile_nationality: "Indonesia",
        profile_religion: "Islam",
        user_id: 1,
        created_at: isoMinutesAgo(5900),
        updated_at: isoMinutesAgo(200),
      },
      {
        id: 2,
        profile_fullname: "Sara Manager",
        profile_gender: "Female",
        profile_place_of_birth: "Bandung",
        profile_date_of_birth: "1990-05-14",
        profile_marital_status: "Married",
        profile_nationality: "Indonesia",
        profile_religion: "Islam",
        user_id: 2,
        created_at: isoMinutesAgo(5600),
        updated_at: isoMinutesAgo(180),
      },
      {
        id: 3,
        profile_fullname: "Agus Engineer",
        profile_gender: "Male",
        profile_place_of_birth: "Surabaya",
        profile_date_of_birth: "1994-08-24",
        profile_marital_status: "Single",
        profile_nationality: "Indonesia",
        profile_religion: "Islam",
        user_id: 3,
        created_at: isoMinutesAgo(5300),
        updated_at: isoMinutesAgo(120),
      },
      {
        id: 4,
        profile_fullname: "Dina Engineer",
        profile_gender: "Female",
        profile_place_of_birth: "Yogyakarta",
        profile_date_of_birth: "1996-02-11",
        profile_marital_status: "Single",
        profile_nationality: "Indonesia",
        profile_religion: "Islam",
        user_id: 4,
        created_at: isoMinutesAgo(5200),
        updated_at: isoMinutesAgo(90),
      },
      {
        id: 5,
        profile_fullname: "Rani HR",
        profile_gender: "Female",
        profile_place_of_birth: "Semarang",
        profile_date_of_birth: "1991-07-19",
        profile_marital_status: "Married",
        profile_nationality: "Indonesia",
        profile_religion: "Islam",
        user_id: 5,
        created_at: isoMinutesAgo(5100),
        updated_at: isoMinutesAgo(80),
      },
      {
        id: 6,
        profile_fullname: "Budi Learning",
        profile_gender: "Male",
        profile_place_of_birth: "Malang",
        profile_date_of_birth: "1993-11-03",
        profile_marital_status: "Single",
        profile_nationality: "Indonesia",
        profile_religion: "Islam",
        user_id: 6,
        created_at: isoMinutesAgo(5000),
        updated_at: isoMinutesAgo(70),
      },
    ],
    companies: [
      {
        id: 1,
        company_name: "PT Dadakan Digital",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
      {
        id: 2,
        company_name: "PT Lean Works",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
    ],
    directorats: [
      {
        id: 1,
        directorat_name: "Operations",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
      {
        id: 2,
        directorat_name: "Technology",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
    ],
    personel_areas: [
      {
        id: 1,
        personel_area_text: "Head Office",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
      {
        id: 2,
        personel_area_text: "Plant Area",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
    ],
    personel_sub_areas: [
      {
        id: 1,
        personel_sub_area_text: "North Zone",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
      {
        id: 2,
        personel_sub_area_text: "South Zone",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
    ],
    plant_areas: [
      {
        id: 1,
        plant_area_name: "Jakarta",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
      {
        id: 2,
        plant_area_name: "Surabaya",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
    ],
    organizations: [
      {
        id: 1,
        organization_name: "Operations Excellence",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
      {
        id: 2,
        organization_name: "Product Engineering",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
    ],
    departments: [
      {
        id: 1,
        department_name: "Operations Delivery",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
      {
        id: 2,
        department_name: "Frontend Platform",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
    ],
    organization_functions: [
      {
        id: 1,
        organization_function_name: "Plant Leadership",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
      {
        id: 2,
        organization_function_name: "Frontend Delivery",
        created_at: isoMinutesAgo(7000),
        updated_at: isoMinutesAgo(7000),
      },
    ],
    competency_levels: [
      {
        id: 1,
        competency_level_title: "L1",
        competency_level_name: "Foundation",
        competency_level_description: "Basic competency understanding",
        created_at: isoMinutesAgo(6500),
        updated_at: isoMinutesAgo(6500),
      },
      {
        id: 2,
        competency_level_title: "L2",
        competency_level_name: "Intermediate",
        competency_level_description: "Solid daily execution capability",
        created_at: isoMinutesAgo(6500),
        updated_at: isoMinutesAgo(6500),
      },
      {
        id: 3,
        competency_level_title: "L3",
        competency_level_name: "Advanced",
        competency_level_description: "Able to lead and improve others",
        created_at: isoMinutesAgo(6500),
        updated_at: isoMinutesAgo(6500),
      },
    ],
    competencies: [
      {
        id: 1,
        competency_name: "Leadership",
        created_at: isoMinutesAgo(6400),
        updated_at: isoMinutesAgo(6400),
      },
      {
        id: 2,
        competency_name: "Safety",
        created_at: isoMinutesAgo(6400),
        updated_at: isoMinutesAgo(6400),
      },
      {
        id: 3,
        competency_name: "Vue Development",
        created_at: isoMinutesAgo(6400),
        updated_at: isoMinutesAgo(6400),
      },
      {
        id: 4,
        competency_name: "Communication",
        created_at: isoMinutesAgo(6400),
        updated_at: isoMinutesAgo(6400),
      },
      {
        id: 5,
        competency_name: "Facilitation",
        created_at: isoMinutesAgo(6400),
        updated_at: isoMinutesAgo(6400),
      },
      {
        id: 6,
        competency_name: "Process Improvement",
        created_at: isoMinutesAgo(6400),
        updated_at: isoMinutesAgo(6400),
      },
    ],
    trainings: [
      {
        id: 1,
        training_job_competency_function: "Leadership",
        training_job_course_function: "People Management",
        training_title: "Leadership Essentials",
        training_level: "Basic",
        training_target_group: "Supervisor",
        training_notes: "Baru",
        training_delivery_method: "Classroom",
        training_program_duration: 3,
        training_day_duration: 2,
        training_hours_duration: 12,
        training_objective: "Build core leadership habits",
        training_content: "Feedback, delegation, planning",
        training_competency_level_stack_key: 1,
        competency_id: 1,
        created_at: isoMinutesAgo(6300),
        updated_at: isoMinutesAgo(6300),
      },
      {
        id: 2,
        training_job_competency_function: "Leadership",
        training_job_course_function: "Advanced Leadership",
        training_title: "Leading Teams",
        training_level: "Intermediate",
        training_target_group: "Manager",
        training_notes: "Baru",
        training_delivery_method: "Workshop",
        training_program_duration: 4,
        training_day_duration: 3,
        training_hours_duration: 18,
        training_objective: "Strengthen delivery leadership",
        training_content: "Coaching and execution",
        training_competency_level_stack_key: 2,
        competency_id: 1,
        created_at: isoMinutesAgo(6200),
        updated_at: isoMinutesAgo(6200),
      },
      {
        id: 3,
        training_job_competency_function: "Safety",
        training_job_course_function: "Plant Safety",
        training_title: "Industrial Safety",
        training_level: "Basic",
        training_target_group: "Plant Teams",
        training_notes: "Baru",
        training_delivery_method: "Classroom",
        training_program_duration: 2,
        training_day_duration: 1,
        training_hours_duration: 8,
        training_objective: "Reduce avoidable incidents",
        training_content: "Safety procedures and reporting",
        training_competency_level_stack_key: 1,
        competency_id: 2,
        created_at: isoMinutesAgo(6200),
        updated_at: isoMinutesAgo(6200),
      },
      {
        id: 4,
        training_job_competency_function: "Frontend",
        training_job_course_function: "Vue",
        training_title: "Vue Frontend Fundamentals",
        training_level: "Basic",
        training_target_group: "Frontend Engineers",
        training_notes: "Baru",
        training_delivery_method: "Online",
        training_program_duration: 5,
        training_day_duration: 5,
        training_hours_duration: 20,
        training_objective: "Ship maintainable Vue apps",
        training_content: "Routing, state, TSX",
        training_competency_level_stack_key: 1,
        competency_id: 3,
        created_at: isoMinutesAgo(6100),
        updated_at: isoMinutesAgo(6100),
      },
      {
        id: 5,
        training_job_competency_function: "Frontend",
        training_job_course_function: "Vue",
        training_title: "Advanced Vue Architecture",
        training_level: "Advance",
        training_target_group: "Senior Frontend Engineers",
        training_notes: "Revisi",
        training_delivery_method: "Workshop",
        training_program_duration: 3,
        training_day_duration: 2,
        training_hours_duration: 16,
        training_objective: "Architect large Vue codebases",
        training_content: "Scaling modules and performance",
        training_competency_level_stack_key: 3,
        competency_id: 3,
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
      {
        id: 6,
        training_job_competency_function: "Communication",
        training_job_course_function: "Business Writing",
        training_title: "Business Communication",
        training_level: "Basic",
        training_target_group: "All Employees",
        training_notes: "Baru",
        training_delivery_method: "Online",
        training_program_duration: 2,
        training_day_duration: 2,
        training_hours_duration: 8,
        training_objective: "Communicate clearly with stakeholders",
        training_content: "Writing and verbal communication",
        training_competency_level_stack_key: 1,
        competency_id: 4,
        created_at: isoMinutesAgo(6000),
        updated_at: isoMinutesAgo(6000),
      },
      {
        id: 7,
        training_job_competency_function: "HR",
        training_job_course_function: "Stakeholder Communication",
        training_title: "HR Stakeholder Communication",
        training_level: "Intermediate",
        training_target_group: "HR Teams",
        training_notes: "Baru",
        training_delivery_method: "Workshop",
        training_program_duration: 2,
        training_day_duration: 2,
        training_hours_duration: 10,
        training_objective: "Handle sensitive stakeholder conversations clearly",
        training_content: "Negotiation, conflict handling, escalation paths",
        training_competency_level_stack_key: 2,
        competency_id: 4,
        created_at: isoMinutesAgo(5900),
        updated_at: isoMinutesAgo(5900),
      },
      {
        id: 8,
        training_job_competency_function: "Learning",
        training_job_course_function: "Program Design",
        training_title: "Learning Program Design",
        training_level: "Intermediate",
        training_target_group: "Learning Officers",
        training_notes: "Baru",
        training_delivery_method: "Workshop",
        training_program_duration: 3,
        training_day_duration: 2,
        training_hours_duration: 12,
        training_objective: "Design effective internal learning journeys",
        training_content: "Needs analysis, curriculum mapping, facilitation plans",
        training_competency_level_stack_key: 2,
        competency_id: 5,
        created_at: isoMinutesAgo(5850),
        updated_at: isoMinutesAgo(5850),
      },
      {
        id: 9,
        training_job_competency_function: "Operations Excellence",
        training_job_course_function: "Continuous Improvement",
        training_title: "Continuous Improvement Basics",
        training_level: "Basic",
        training_target_group: "Improvement Champions",
        training_notes: "Baru",
        training_delivery_method: "Classroom",
        training_program_duration: 2,
        training_day_duration: 2,
        training_hours_duration: 8,
        training_objective: "Build a practical improvement mindset",
        training_content: "Problem framing, root cause, action follow-up",
        training_competency_level_stack_key: 1,
        competency_id: 6,
        created_at: isoMinutesAgo(5800),
        updated_at: isoMinutesAgo(5800),
      },
    ],
    positions: [
      {
        id: 1,
        position_name: "Operations Manager",
        created_at: isoMinutesAgo(6700),
        updated_at: isoMinutesAgo(6700),
      },
      {
        id: 2,
        position_name: "Plant Supervisor",
        created_at: isoMinutesAgo(6700),
        updated_at: isoMinutesAgo(6700),
      },
      {
        id: 3,
        position_name: "Frontend Engineer",
        created_at: isoMinutesAgo(6700),
        updated_at: isoMinutesAgo(6700),
      },
      {
        id: 4,
        position_name: "HR Business Partner",
        created_at: isoMinutesAgo(6700),
        updated_at: isoMinutesAgo(6700),
      },
      {
        id: 5,
        position_name: "Learning & Development Officer",
        created_at: isoMinutesAgo(6700),
        updated_at: isoMinutesAgo(6700),
      },
    ],
    requirement_scores: [
      {
        id: 1,
        minimum_score: 4,
        position_id: 1,
        competency_id: 1,
        competency_level_id: 2,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 2,
        minimum_score: 4,
        position_id: 1,
        competency_id: 4,
        competency_level_id: 2,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 3,
        minimum_score: 4,
        position_id: 2,
        competency_id: 2,
        competency_level_id: 2,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 4,
        minimum_score: 3,
        position_id: 2,
        competency_id: 1,
        competency_level_id: 1,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 5,
        minimum_score: 4,
        position_id: 3,
        competency_id: 3,
        competency_level_id: 2,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 6,
        minimum_score: 3,
        position_id: 3,
        competency_id: 4,
        competency_level_id: 1,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 7,
        minimum_score: 4,
        position_id: 4,
        competency_id: 1,
        competency_level_id: 2,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 8,
        minimum_score: 4,
        position_id: 4,
        competency_id: 4,
        competency_level_id: 2,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 9,
        minimum_score: 4,
        position_id: 5,
        competency_id: 5,
        competency_level_id: 2,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
      {
        id: 10,
        minimum_score: 3,
        position_id: 5,
        competency_id: 6,
        competency_level_id: 1,
        created_at: isoMinutesAgo(6600),
        updated_at: isoMinutesAgo(6600),
      },
    ],
    assessment_schedules: [
      {
        id: 1,
        assessment_schedule_title: "Mid Year Review",
        assessment_schedule_description: "First half competency review",
        assessment_schedule_year_period: "2025",
        assessment_schedule_phase_period: "H1",
        assessment_schedule_start_date: "2025-05-01T00:00:00.000Z",
        assessment_schedule_end_date: "2025-05-31T23:59:59.000Z",
        assessment_schedule_is_active: false,
        created_at: isoMinutesAgo(5000),
        updated_at: isoMinutesAgo(5000),
      },
      {
        id: 2,
        assessment_schedule_title: "Annual Review",
        assessment_schedule_description: "Year end competency review",
        assessment_schedule_year_period: "2025",
        assessment_schedule_phase_period: "H2",
        assessment_schedule_start_date: "2025-11-01T00:00:00.000Z",
        assessment_schedule_end_date: "2025-11-30T23:59:59.000Z",
        assessment_schedule_is_active: true,
        created_at: isoMinutesAgo(4900),
        updated_at: isoMinutesAgo(4900),
      },
      {
        id: 3,
        assessment_schedule_title: "Capability Sprint",
        assessment_schedule_description: "Focused follow-up plan for capability gaps",
        assessment_schedule_year_period: "2026",
        assessment_schedule_phase_period: "H1",
        assessment_schedule_start_date: "2026-03-01T00:00:00.000Z",
        assessment_schedule_end_date: "2026-03-31T23:59:59.000Z",
        assessment_schedule_is_active: false,
        created_at: isoMinutesAgo(4800),
        updated_at: isoMinutesAgo(4800),
      },
    ],
    employments: [
      {
        id: 1,
        employment_hiring_date: "2020-01-15T00:00:00.000Z",
        employment_end_date: null,
        employment_group_type_name: "Permanent",
        employment_group_age: "Senior",
        employment_status: "Active",
        employment_position_status: "Definitive",
        employment_wsr: "WSR-001",
        parent_employment_id: null,
        profile_id: 1,
        position_id: 1,
        company_id: 1,
        directorat_id: 1,
        personel_area_id: 1,
        personel_sub_area_id: 1,
        plant_area_id: 1,
        organization_id: 1,
        department_id: 1,
        organization_function_id: 1,
        created_at: isoMinutesAgo(4800),
        updated_at: isoMinutesAgo(200),
      },
      {
        id: 2,
        employment_hiring_date: "2021-03-03T00:00:00.000Z",
        employment_end_date: null,
        employment_group_type_name: "Permanent",
        employment_group_age: "Middle",
        employment_status: "Active",
        employment_position_status: "Definitive",
        employment_wsr: "WSR-002",
        parent_employment_id: 1,
        profile_id: 2,
        position_id: 2,
        company_id: 1,
        directorat_id: 1,
        personel_area_id: 2,
        personel_sub_area_id: 1,
        plant_area_id: 2,
        organization_id: 1,
        department_id: 1,
        organization_function_id: 1,
        created_at: isoMinutesAgo(4700),
        updated_at: isoMinutesAgo(180),
      },
      {
        id: 3,
        employment_hiring_date: "2022-06-20T00:00:00.000Z",
        employment_end_date: null,
        employment_group_type_name: "Permanent",
        employment_group_age: "Junior",
        employment_status: "Active",
        employment_position_status: "Definitive",
        employment_wsr: "WSR-003",
        parent_employment_id: 1,
        profile_id: 3,
        position_id: 3,
        company_id: 2,
        directorat_id: 2,
        personel_area_id: 1,
        personel_sub_area_id: 2,
        plant_area_id: 1,
        organization_id: 2,
        department_id: 2,
        organization_function_id: 2,
        created_at: isoMinutesAgo(4600),
        updated_at: isoMinutesAgo(120),
      },
      {
        id: 4,
        employment_hiring_date: "2023-02-10T00:00:00.000Z",
        employment_end_date: null,
        employment_group_type_name: "Contract",
        employment_group_age: "Junior",
        employment_status: "Active",
        employment_position_status: "Acting",
        employment_wsr: "WSR-004",
        parent_employment_id: 3,
        profile_id: 4,
        position_id: 3,
        company_id: 2,
        directorat_id: 2,
        personel_area_id: 1,
        personel_sub_area_id: 2,
        plant_area_id: 1,
        organization_id: 2,
        department_id: 2,
        organization_function_id: 2,
        created_at: isoMinutesAgo(4500),
        updated_at: isoMinutesAgo(90),
      },
      {
        id: 5,
        employment_hiring_date: "2021-09-06T00:00:00.000Z",
        employment_end_date: null,
        employment_group_type_name: "Permanent",
        employment_group_age: "Middle",
        employment_status: "Active",
        employment_position_status: "Definitive",
        employment_wsr: "WSR-005",
        parent_employment_id: 1,
        profile_id: 5,
        position_id: 4,
        company_id: 1,
        directorat_id: 1,
        personel_area_id: 1,
        personel_sub_area_id: 1,
        plant_area_id: 1,
        organization_id: 1,
        department_id: 1,
        organization_function_id: 1,
        created_at: isoMinutesAgo(4400),
        updated_at: isoMinutesAgo(80),
      },
      {
        id: 6,
        employment_hiring_date: "2024-01-08T00:00:00.000Z",
        employment_end_date: null,
        employment_group_type_name: "Permanent",
        employment_group_age: "Junior",
        employment_status: "Active",
        employment_position_status: "Acting",
        employment_wsr: "WSR-006",
        parent_employment_id: 5,
        profile_id: 6,
        position_id: 5,
        company_id: 1,
        directorat_id: 1,
        personel_area_id: 1,
        personel_sub_area_id: 1,
        plant_area_id: 1,
        organization_id: 1,
        department_id: 1,
        organization_function_id: 1,
        created_at: isoMinutesAgo(4300),
        updated_at: isoMinutesAgo(70),
      },
    ],
    assessment_records: [
      {
        id: 1,
        assessment_score: 4,
        competency_id: 2,
        competency_level_id: 2,
        employment_id: 2,
        gap_score: 0,
        minimum_score: 4,
        parent_employment_id: 1,
        position_id: 2,
        training_id: 3,
        idp_exposure_experience: null,
        idp_status: "done",
        assessment_schedule_id: 1,
        created_at: isoMinutesAgo(3000),
        updated_at: isoMinutesAgo(3000),
      },
      {
        id: 2,
        assessment_score: 2,
        competency_id: 1,
        competency_level_id: 1,
        employment_id: 2,
        gap_score: 1,
        minimum_score: 3,
        parent_employment_id: 1,
        position_id: 2,
        training_id: 1,
        idp_exposure_experience: null,
        idp_status: "on-going",
        assessment_schedule_id: 1,
        created_at: isoMinutesAgo(3000),
        updated_at: isoMinutesAgo(3000),
      },
      {
        id: 3,
        assessment_score: 4,
        competency_id: 3,
        competency_level_id: 2,
        employment_id: 3,
        gap_score: 0,
        minimum_score: 4,
        parent_employment_id: 1,
        position_id: 3,
        training_id: 4,
        idp_exposure_experience: null,
        idp_status: "done",
        assessment_schedule_id: 2,
        created_at: isoMinutesAgo(2500),
        updated_at: isoMinutesAgo(2500),
      },
      {
        id: 4,
        assessment_score: 2,
        competency_id: 4,
        competency_level_id: 1,
        employment_id: 3,
        gap_score: 1,
        minimum_score: 3,
        parent_employment_id: 1,
        position_id: 3,
        training_id: 6,
        idp_exposure_experience: null,
        idp_status: "pending",
        assessment_schedule_id: 2,
        created_at: isoMinutesAgo(2500),
        updated_at: isoMinutesAgo(2500),
      },
      {
        id: 5,
        assessment_score: 3,
        competency_id: 3,
        competency_level_id: 2,
        employment_id: 4,
        gap_score: 1,
        minimum_score: 4,
        parent_employment_id: 3,
        position_id: 3,
        training_id: 5,
        idp_exposure_experience: null,
        idp_status: "on-going",
        assessment_schedule_id: 2,
        created_at: isoMinutesAgo(2400),
        updated_at: isoMinutesAgo(2400),
      },
      {
        id: 6,
        assessment_score: 3,
        competency_id: 4,
        competency_level_id: 1,
        employment_id: 4,
        gap_score: 0,
        minimum_score: 3,
        parent_employment_id: 3,
        position_id: 3,
        training_id: 6,
        idp_exposure_experience: null,
        idp_status: "done",
        assessment_schedule_id: 2,
        created_at: isoMinutesAgo(2400),
        updated_at: isoMinutesAgo(2400),
      },
      {
        id: 7,
        assessment_score: 4,
        competency_id: 1,
        competency_level_id: 2,
        employment_id: 5,
        gap_score: 0,
        minimum_score: 4,
        parent_employment_id: 1,
        position_id: 4,
        training_id: 2,
        idp_exposure_experience: null,
        idp_status: "done",
        assessment_schedule_id: 2,
        created_at: isoMinutesAgo(2350),
        updated_at: isoMinutesAgo(2350),
      },
      {
        id: 8,
        assessment_score: 3,
        competency_id: 4,
        competency_level_id: 2,
        employment_id: 5,
        gap_score: 1,
        minimum_score: 4,
        parent_employment_id: 1,
        position_id: 4,
        training_id: 7,
        idp_exposure_experience: null,
        idp_status: "on-going",
        assessment_schedule_id: 2,
        created_at: isoMinutesAgo(2350),
        updated_at: isoMinutesAgo(2350),
      },
    ],
    periodical_general_assessments: [
      {
        id: 1,
        employment_id: 2,
        assessment_schedule_id: 1,
        parameters_name: "education",
        parameters_value: "Safety leadership refresh",
        status: "done",
        created_at: isoMinutesAgo(2950),
        updated_at: isoMinutesAgo(2950),
      },
      {
        id: 2,
        employment_id: 2,
        assessment_schedule_id: 1,
        parameters_name: "exposure",
        parameters_value: "Lead plant retro",
        status: "on-going",
        created_at: isoMinutesAgo(2950),
        updated_at: isoMinutesAgo(2950),
      },
      {
        id: 3,
        employment_id: 2,
        assessment_schedule_id: 1,
        parameters_name: "experience",
        parameters_value: "Weekly shift coordination",
        status: "done",
        created_at: isoMinutesAgo(2950),
        updated_at: isoMinutesAgo(2950),
      },
      {
        id: 4,
        employment_id: 3,
        assessment_schedule_id: 2,
        parameters_name: "education",
        parameters_value: "Frontend architecture clinic",
        status: "done",
        created_at: isoMinutesAgo(2450),
        updated_at: isoMinutesAgo(2450),
      },
      {
        id: 5,
        employment_id: 3,
        assessment_schedule_id: 2,
        parameters_name: "exposure",
        parameters_value: "Cross-team release support",
        status: "pending",
        created_at: isoMinutesAgo(2450),
        updated_at: isoMinutesAgo(2450),
      },
      {
        id: 6,
        employment_id: 3,
        assessment_schedule_id: 2,
        parameters_name: "experience",
        parameters_value: "Lead one dashboard feature",
        status: "on-going",
        created_at: isoMinutesAgo(2450),
        updated_at: isoMinutesAgo(2450),
      },
      {
        id: 7,
        employment_id: 4,
        assessment_schedule_id: 2,
        parameters_name: "education",
        parameters_value: "Accessibility review workshop",
        status: "done",
        created_at: isoMinutesAgo(2380),
        updated_at: isoMinutesAgo(2380),
      },
      {
        id: 8,
        employment_id: 4,
        assessment_schedule_id: 2,
        parameters_name: "exposure",
        parameters_value: "Own one release QA checklist",
        status: "on-going",
        created_at: isoMinutesAgo(2380),
        updated_at: isoMinutesAgo(2380),
      },
      {
        id: 9,
        employment_id: 4,
        assessment_schedule_id: 2,
        parameters_name: "experience",
        parameters_value: "Pair on one production issue investigation",
        status: "pending",
        created_at: isoMinutesAgo(2380),
        updated_at: isoMinutesAgo(2380),
      },
      {
        id: 10,
        employment_id: 5,
        assessment_schedule_id: 3,
        parameters_name: "education",
        parameters_value: "Employment law refresher class",
        status: "done",
        created_at: isoMinutesAgo(2300),
        updated_at: isoMinutesAgo(2300),
      },
      {
        id: 11,
        employment_id: 5,
        assessment_schedule_id: 3,
        parameters_name: "exposure",
        parameters_value: "Lead one policy communication roadshow",
        status: "on-going",
        created_at: isoMinutesAgo(2300),
        updated_at: isoMinutesAgo(2300),
      },
      {
        id: 12,
        employment_id: 5,
        assessment_schedule_id: 3,
        parameters_name: "experience",
        parameters_value: "Coordinate one cross-department workforce review",
        status: "done",
        created_at: isoMinutesAgo(2300),
        updated_at: isoMinutesAgo(2300),
      },
    ],
    certifications: [
      {
        id: 1,
        certification_name: "Industrial Safety Passport",
        certification_status: "active",
        certification_description: "Mandatory safety compliance certificate for plant supervisors.",
        employment_id: 2,
        created_at: isoMinutesAgo(2200),
        updated_at: isoMinutesAgo(2200),
      },
      {
        id: 2,
        certification_name: "Vue Associate Engineer",
        certification_status: "active",
        certification_description: "Internal frontend engineering certification for Vue delivery teams.",
        employment_id: 3,
        created_at: isoMinutesAgo(2150),
        updated_at: isoMinutesAgo(2150),
      },
      {
        id: 3,
        certification_name: "Frontend Accessibility Fundamentals",
        certification_status: "pending",
        certification_description: "Accessibility pathway assigned for junior frontend engineers.",
        employment_id: 4,
        created_at: isoMinutesAgo(2100),
        updated_at: isoMinutesAgo(2100),
      },
      {
        id: 4,
        certification_name: "HR Compliance Certification",
        certification_status: "active",
        certification_description: "HR governance and policy administration certification.",
        employment_id: 5,
        created_at: isoMinutesAgo(2050),
        updated_at: isoMinutesAgo(2050),
      },
      {
        id: 5,
        certification_name: "Learning Facilitator Badge",
        certification_status: "active",
        certification_description: "Baseline facilitation badge for internal learning delivery.",
        employment_id: 6,
        created_at: isoMinutesAgo(2000),
        updated_at: isoMinutesAgo(2000),
      },
    ],
    bucket_categories: [
      {
        id: 1,
        bucket_category_name: "Public",
        bucket_category_description: "Visible to everyone",
        created_at: isoMinutesAgo(4200),
        updated_at: isoMinutesAgo(4200),
      },
      {
        id: 2,
        bucket_category_name: "Private",
        bucket_category_description: "Scoped per owner",
        created_at: isoMinutesAgo(4200),
        updated_at: isoMinutesAgo(4200),
      },
    ],
    publication_categories: [
      {
        id: 1,
        publication_category_name: "Handbook",
        publication_category_description: "Knowledge handbook",
        created_at: isoMinutesAgo(4200),
        updated_at: isoMinutesAgo(4200),
      },
      {
        id: 2,
        publication_category_name: "SOP",
        publication_category_description: "Operational procedures",
        created_at: isoMinutesAgo(4200),
        updated_at: isoMinutesAgo(4200),
      },
      {
        id: 3,
        publication_category_name: "Engineering",
        publication_category_description: "Engineering materials",
        created_at: isoMinutesAgo(4200),
        updated_at: isoMinutesAgo(4200),
      },
    ],
    buckets: [
      {
        id: 1,
        bucket_name: "Public Knowledge Base",
        bucket_description: "Shared learning material for all employees",
        bucket_created_by: "demo@example.com",
        bucket_category_id: 1,
        bucket_author_employment_id: 1,
        bucket_has_public_access: true,
        created_at: isoMinutesAgo(4100),
        updated_at: isoMinutesAgo(4100),
      },
      {
        id: 2,
        bucket_name: "Engineering Docs",
        bucket_description: "Private frontend and release notes",
        bucket_created_by: "agus.engineer@example.com",
        bucket_category_id: 2,
        bucket_author_employment_id: 3,
        bucket_has_public_access: false,
        created_at: isoMinutesAgo(4100),
        updated_at: isoMinutesAgo(4100),
      },
      {
        id: 3,
        bucket_name: "Operations Playbooks",
        bucket_description: "Private plant and operations documents",
        bucket_created_by: "sara.manager@example.com",
        bucket_category_id: 2,
        bucket_author_employment_id: 2,
        bucket_has_public_access: false,
        created_at: isoMinutesAgo(4100),
        updated_at: isoMinutesAgo(4100),
      },
      {
        id: 4,
        bucket_name: "HR Toolkit",
        bucket_description: "Policies, onboarding, and workforce support assets",
        bucket_created_by: "rani.hr@example.com",
        bucket_category_id: 2,
        bucket_author_employment_id: 5,
        bucket_has_public_access: false,
        created_at: isoMinutesAgo(4050),
        updated_at: isoMinutesAgo(4050),
      },
    ],
    publications: [
      {
        id: 1,
        publication_title: "Frontend Checklist",
        publication_slug: "frontend-checklist",
        publication_description: "Lightweight checklist for shipping dashboard changes",
        publication_is_verified: true,
        publication_category_id: 3,
        bucket_id: 2,
        created_at: isoMinutesAgo(3900),
        updated_at: isoMinutesAgo(3900),
      },
      {
        id: 2,
        publication_title: "Plant Safety Handbook",
        publication_slug: "plant-safety-handbook",
        publication_description: "Core operational safety handbook",
        publication_is_verified: true,
        publication_category_id: 1,
        bucket_id: 1,
        created_at: isoMinutesAgo(3900),
        updated_at: isoMinutesAgo(3900),
      },
      {
        id: 3,
        publication_title: "Team Rituals",
        publication_slug: "team-rituals",
        publication_description: "Working agreement for product teams",
        publication_is_verified: false,
        publication_category_id: 1,
        bucket_id: 1,
        created_at: isoMinutesAgo(3800),
        updated_at: isoMinutesAgo(3800),
      },
      {
        id: 4,
        publication_title: "Onboarding Playbook",
        publication_slug: "onboarding-playbook",
        publication_description: "Starter handbook for new hires and people managers.",
        publication_is_verified: true,
        publication_category_id: 1,
        bucket_id: 4,
        created_at: isoMinutesAgo(3750),
        updated_at: isoMinutesAgo(3750),
      },
      {
        id: 5,
        publication_title: "Frontend Release SOP",
        publication_slug: "frontend-release-sop",
        publication_description: "Release checklist and rollback procedure for frontend deployments.",
        publication_is_verified: true,
        publication_category_id: 2,
        bucket_id: 2,
        created_at: isoMinutesAgo(3700),
        updated_at: isoMinutesAgo(3700),
      },
    ],
    publication_storages: [
      {
        id: 1,
        publication_id: 1,
        document_extension: "pdf",
        document_type: "application/pdf",
        document_name: "frontend-checklist",
        document_hash_name: "frontend-checklist",
        document_path: "mock-publications",
        document_storage_path: "mock-publications/frontend-checklist.pdf",
        document_description:
          "Shipping checklist for frontend dashboard updates and hotfixes.",
        document_size: "128 KB",
        document_uuid: "frontend-checklist-uuid",
        storageable_id: 1,
        storageable_type: "Publication",
        created_at: isoMinutesAgo(3900),
        updated_at: isoMinutesAgo(3900),
      },
      {
        id: 2,
        publication_id: 2,
        document_extension: "pdf",
        document_type: "application/pdf",
        document_name: "plant-safety-handbook",
        document_hash_name: "plant-safety-handbook",
        document_path: "mock-publications",
        document_storage_path: "mock-publications/plant-safety-handbook.pdf",
        document_description:
          "Core operating handbook covering safety routines and incident response.",
        document_size: "256 KB",
        document_uuid: "plant-safety-handbook-uuid",
        storageable_id: 2,
        storageable_type: "Publication",
        created_at: isoMinutesAgo(3900),
        updated_at: isoMinutesAgo(3900),
      },
      {
        id: 3,
        publication_id: 3,
        document_extension: "pdf",
        document_type: "application/pdf",
        document_name: "team-rituals",
        document_hash_name: "team-rituals",
        document_path: "mock-publications",
        document_storage_path: "mock-publications/team-rituals.pdf",
        document_description:
          "Working agreement and recurring rituals for cross-functional teams.",
        document_size: "96 KB",
        document_uuid: "team-rituals-uuid",
        storageable_id: 3,
        storageable_type: "Publication",
        created_at: isoMinutesAgo(3800),
        updated_at: isoMinutesAgo(3800),
      },
      {
        id: 4,
        publication_id: 4,
        document_extension: "pdf",
        document_type: "application/pdf",
        document_name: "onboarding-playbook",
        document_hash_name: "onboarding-playbook",
        document_path: "mock-publications",
        document_storage_path: "mock-publications/onboarding-playbook.pdf",
        document_description:
          "Onboarding guide for new hires, buddies, and people managers.",
        document_size: "144 KB",
        document_uuid: "onboarding-playbook-uuid",
        storageable_id: 4,
        storageable_type: "Publication",
        created_at: isoMinutesAgo(3750),
        updated_at: isoMinutesAgo(3750),
      },
      {
        id: 5,
        publication_id: 5,
        document_extension: "pdf",
        document_type: "application/pdf",
        document_name: "frontend-release-sop",
        document_hash_name: "frontend-release-sop",
        document_path: "mock-publications",
        document_storage_path: "mock-publications/frontend-release-sop.pdf",
        document_description:
          "Release procedure, rollback plan, and validation checklist for frontend deploys.",
        document_size: "132 KB",
        document_uuid: "frontend-release-sop-uuid",
        storageable_id: 5,
        storageable_type: "Publication",
        created_at: isoMinutesAgo(3700),
        updated_at: isoMinutesAgo(3700),
      },
    ],
    password_reset_requests: [],
  };
}

module.exports = {
  demoPassword,
  tokens,
  createSeedState,
};
