import type { AssessmentRecordResource } from "./AssessmentRecord";
import type { AssessmentScheduleResource } from "./AssessmentSchedule";
import type { CertificationResource } from "./Certification";
import type { CompanyResource } from "./Company";
import type { DirectoratResource } from "./Directorat";
import type { PersonelAreaResource } from "./PersonelArea";
import type { PersonelSubAreaResource } from "./PersonelSubArea";
import type { PlantAreaResource } from "./PlantArea";
import type { PositionResource } from "./Position";
import type { ProfileResource } from "./Profile";

export declare type EmploymentResource = {
  employment_hiring_date: string | null;
  employment_end_date: string | null;
  employment_group_type_name: string | null;
  employment_group_age: string | null;
  employment_status: string | null;
  employment_position_status: string | null;
  employment_wsr: string | null;
  parent_employment_id: number | null;
  profile_id: number | null;
  position_id: number | null;
  company_id: number | null;
  directorat_id: number | null;
  personel_area_id: number | null;
  personel_sub_area_id: number | null;
  plant_area_id: number | null;
  position: PositionResource | null;
  profile: ProfileResource | null;
  company: CompanyResource | null;
  directorat: DirectoratResource | null;
  personel_area: PersonelAreaResource | null;
  personel_sub_area: PersonelSubAreaResource | null;
  plant_area: PlantAreaResource | null;
  parent?: EmploymentResource | null;
  children?: EmploymentResource[] | [];
  assessmentRecords?: AssessmentRecordResource[] | [];
  assessment_records?: AssessmentRecordResource[] | [];
  appliedAssessmentLogs?: AssessmentScheduleResource[] | [];
  certifications?: CertificationResource[] | [];
};
export declare type EmploymentCollections = EmploymentResource[];
